### ISSUE TITLE
Is this board could enable HDMI output?

### ISSUE THREAD

**Issue by lclancey** [hoangstark/whiteblack-hackintosh#1]
I used this efi for a few months and this worked great on my PC. Many thanks my friend.

But there is a minor issue. I am using 2 displayers on RX470, one for DP, one for HDMI, that's OK. But I tried to remove my RX470 for some reason last week, and use Hackintool to enable HDMI port of motherboard working, just can't.

Do you have any sollution please?

8100+b360m mortar+rx470+sm961

**Comment by h5tark** [comment]
Did you turn-off multi monitor in BIOS after removing RX470? I didn't test with iGPU only.
